### ISSUE TITLE
v2.0

### ISSUE THREAD

**Issue by WardsParadox** [munkireport/munkireport#1]
When a client submits to the processor, an error reports:
syntax error, unexpected in <b>/munkireport_processor</b> on line 72

**Comment by bochoven** [comment]
Did you update the munkireport module?

**Comment by WardsParadox** [comment]
Yes, it's on v2.0 now.

**Comment by bochoven** [comment]
Can't reproduce the issue.. You're not including another version of the module?

**Comment by bochoven** [comment]
Should be fixed with 66d2df4
